### ISSUE TITLE
Correct Value for the CFA

### ISSUE THREAD

**Issue by lks9** [lks9/angr#2]
**Descritption**
Better than the approximation #1.

**Depends on**
#1

**Comment by ducorduck** [comment]
partially implemented in new_cfa_computation branch (also in cle repository) but require too much processing power. Because of that we decided to not merge the implementation into main.
Here are some of the runtime of the test_dwarf_variables.py:
(base)
1. time: 251.503s
2. time: 254.464s
3. time: 257.314s

(1. Iteration of the implementation)
1. time: 420.064s
2. time: 403.880s
3. time: 400.752s

(2. Iteration of the implementation)
1. time: 453.364s
2. time: 391.724s
3. time: 389.555s
