### ISSUE TITLE
Get variables from name

### ISSUE THREAD

**Issue by lks9** [lks9/angr#4]
**Descritption**
```
cu.global_vars["x"]
x = func.local_vars["x"]
lexical_block.local_vars["x"]
```
instead of / in addition to
```
local_vars = func.local_variables

for local_var in local_vars:
	if local_var.name == 'x':
		x = local_var
```

**Depends on**
#6 

**Estimated time**

**Comment by ducorduck** [comment]
@lks9  I've implemented the first 2 part which is the global_vars as well as the local_vars of func (Subprogram) in this [pull request](https://github.com/lks9/cle/pull/1) but I'm not quite sure if it is good because it require linearly parsing the list to create the dictionary. So every time we access .global_vars it create a new dictionary.

**Comment by lks9** [comment]
Thanks for the implementation. This is how I wanted it. Two points:

* A function could contain multiple local variables with the same name (in different lexical blocks). Therefore the dependency #6.
* And yes, it seems to be a bit inefficient. When you do it during the DWARF loading step, it could be more efficient. I have figured out that the global and local variables are both originally added in the method `_load_dies` which is in `cle/backends/elf/elf.py`.
